[package]
name = "blanco"
version = "0.1.0"
edition = "2021"

[dependencies]
gpui = "0.2.0"
gpui-component = { path = "../../gpui-component/crates/ui", features = ["tree-sitter-languages"] }
anyhow = { version = "1", features = ["backtrace"] }
env_logger = "0.11"
log = "0.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1"
smol = "1"
async-compat = "0.2"
dirs = "5"
sqlx = { version = "0.8", features = ["runtime-tokio", "sqlite", "postgres"] }
tokio = { version = "1", features = ["rt", "rt-multi-thread", "macros"] }
chrono = "0.4"
rust-embed = { version = "8", features = ["interpolate-folder-path"] }
