#!/usr/bin/env python3
"""Regenerate the built-in SQL function catalogs under crates/blanco/src/sql/functions/.

Each dialect is pulled from a live server in docker-compose.yml, using only the
standard library plus the client each container already ships:

    postgres    psql (host binary) against postgrestestdb_ssl on 127.0.0.1:5488
                pg_catalog.pg_proc, filtered down to user-facing functions
    mysql       `docker exec` into the mariadb container: mysql.help_topic
                (the `HELP` tables, which carry a Syntax block per function)
    clickhouse  HTTP interface on 127.0.0.1:8124: system.functions
    sqlite      Python's sqlite3 module: pragma_function_list. SQLite has no
                signature catalog, so sqlite.rs is curated by hand and this
                subcommand only lints it for missing names.

MSSQL has no catalog of built-ins at all, so mssql.rs is curated by hand.

    python3 scripts/extract-sql-functions.py all
    python3 scripts/extract-sql-functions.py postgres
"""

import argparse
import base64
import json
import os
import re
import sqlite3
import subprocess
import sys
import urllib.request

HERE = os.path.dirname(os.path.abspath(__file__))
OUT_DIR = os.path.join(HERE, "..", "crates", "blanco", "src", "sql", "functions")


# ---------------------------------------------------------------------------
# Output


def rust_str(text):
    """A Rust string literal. Non-ASCII stays raw; Rust source is UTF-8."""
    out = []
    for ch in text:
        if ch == "\\":
            out.append("\\\\")
        elif ch == '"':
            out.append('\\"')
        elif ch == "\n":
            out.append("\\n")
        elif ch == "\t":
            out.append("\\t")
        elif ch == "\r":
            continue
        elif ord(ch) < 0x20:
            out.append("\\u{%x}" % ord(ch))
        else:
            out.append(ch)
    return '"' + "".join(out) + '"'


def emit(dialect, entries, source_note):
    """Write `<dialect>.rs` holding a sorted `FUNCTIONS` slice.

    `entries` is a list of dicts with `name`, `parameters` (list of str),
    `return_type` (str) and `documentation` (str, markdown).
    """
    seen = set()
    unique = []
    for entry in entries:
        key = (entry["name"], tuple(entry["parameters"]))
        if key in seen:
            continue
        seen.add(key)
        unique.append(entry)
    # The Rust side binary-searches on the lowercased name, and overloads of one
    # name must be adjacent.
    unique.sort(key=lambda e: (e["name"].lower(), len(e["parameters"]), e["parameters"]))

    path = os.path.join(OUT_DIR, f"{dialect}.rs")
    with open(path, "w") as out:
        out.write(f"// Generated by scripts/extract-sql-functions.py from {source_note}.\n")
        out.write("// Do not edit by hand.\n\n")
        out.write("use super::FunctionSignature;\n\n")
        out.write("#[rustfmt::skip]\npub(super) const FUNCTIONS: &[FunctionSignature] = &[\n")
        for entry in unique:
            params = ", ".join(rust_str(p) for p in entry["parameters"])
            out.write("    FunctionSignature {\n")
            out.write(f"        name: {rust_str(entry['name'])},\n")
            out.write(f"        parameters: &[{params}],\n")
            out.write(f"        return_type: {rust_str(entry['return_type'])},\n")
            out.write(f"        documentation: {rust_str(entry['documentation'])},\n")
            out.write("    },\n")
        out.write("];\n")
    names = {e["name"] for e in unique}
    print(f"{dialect}: {len(unique)} signatures, {len(names)} functions -> {os.path.relpath(path)}")


def split_top_level(text, separators=","):
    """Split on `separators` outside (), [] and quotes."""
    parts, depth, current, quote = [], 0, [], None
    for ch in text:
        if quote:
            current.append(ch)
            if ch == quote:
                quote = None
            continue
        if ch in "'\"`":
            quote = ch
            current.append(ch)
        elif ch in "([{":
            depth += 1
            current.append(ch)
        elif ch in ")]}":
            depth = max(0, depth - 1)
            current.append(ch)
        elif ch in separators and depth == 0:
            parts.append("".join(current).strip())
            current = []
        else:
            current.append(ch)
    tail = "".join(current).strip()
    if tail or parts:
        parts.append(tail)
    return [p for p in parts if p]


def trim_paragraphs(text, limit):
    """Keep whole paragraphs up to roughly `limit` characters."""
    if len(text) <= limit:
        return text
    kept, total = [], 0
    for paragraph in text.split("\n\n"):
        if kept and total + len(paragraph) > limit:
            break
        kept.append(paragraph)
        total += len(paragraph) + 2
    return "\n\n".join(kept).rstrip() + "\n\n…"


def parse_call_syntax(syntax):
    """`name(a, b[, c])` -> (name, ["a", "b", "[, c]"]) or None."""
    match = re.match(r"^\s*([A-Za-z_][A-Za-z0-9_.]*)\s*\((.*)\)\s*$", syntax, re.S)
    if not match:
        return None
    name, inner = match.group(1), match.group(2).strip()
    return name, split_top_level(inner) if inner else []


# ---------------------------------------------------------------------------
# PostgreSQL

PG_EXCLUDED_DOC_PATTERNS = [
    r"^implementation of .* operator$",
    r"I/O",
    r"^less-equal-greater$",
    r"^hash$",
    r"^smaller of two$",
    r"^larger of two$",
    r"support",
    r"^aggregate .* function$",
    r"for use by pg_upgrade",
    r"^\(internal\)$",
    r"internal use",
    r"^planner support",
]
PG_EXCLUDED_NAME_SUFFIXES = (
    "_in", "_out", "_recv", "_send", "_cmp", "_lt", "_le", "_gt", "_ge", "_eq", "_ne",
    "_support", "_sel", "_joinsel", "_typmod_in", "_typmod_out", "_subtype_diff", "_hash",
    "_hash_extended", "_sortsupport", "_options", "_restrict", "_transfn", "_finalfn",
    "_combine", "_serialize", "_deserialize", "_accum", "_worker", "_inv", "_analyze",
    "_larger", "_smaller", "_transfn_internal",
)
PG_EXCLUDED_NAME_PREFIXES = (
    "_", "binary_upgrade", "RI_FKey", "gin_", "gist_", "brin_", "spg_", "amvalidate", "aclitem",
    "bt", "hash", "tsm_", "ts_debug",
)
PG_INTERNAL_TYPES = re.compile(
    r"\b(internal|cstring|opaque|trigger|event_trigger|language_handler|fdw_handler|"
    r"index_am_handler|tsm_handler|table_am_handler)\b"
)


def postgres(args):
    env = dict(os.environ, PGPASSWORD=args.pg_password)
    query = """
        SELECT p.proname,
               pg_get_function_arguments(p.oid),
               pg_get_function_result(p.oid),
               coalesce(obj_description(p.oid, 'pg_proc'), ''),
               p.prokind
        FROM pg_proc p
        JOIN pg_namespace n ON n.oid = p.pronamespace
        WHERE n.nspname = 'pg_catalog' AND p.prokind IN ('f', 'a', 'w')
        ORDER BY 1, 2
    """
    result = subprocess.run(
        [
            "psql", "-h", args.pg_host, "-p", str(args.pg_port), "-U", args.pg_user,
            "-d", args.pg_database, "-At", "-F", "\x01", "-R", "\x02", "-c", query,
        ],
        env=env, check=True, capture_output=True, text=True,
    )
    version = subprocess.run(
        ["psql", "-h", args.pg_host, "-p", str(args.pg_port), "-U", args.pg_user,
         "-d", args.pg_database, "-At", "-c", "SHOW server_version"],
        env=env, check=True, capture_output=True, text=True,
    ).stdout.strip()

    entries = []
    for record in result.stdout.split("\x02"):
        record = record.strip("\n")
        if not record:
            continue
        name, arguments, return_type, doc, kind = record.split("\x01")
        if name.startswith(PG_EXCLUDED_NAME_PREFIXES) or name.endswith(PG_EXCLUDED_NAME_SUFFIXES):
            continue
        if any(re.search(p, doc, re.I) for p in PG_EXCLUDED_DOC_PATTERNS):
            continue
        if PG_INTERNAL_TYPES.search(arguments) or PG_INTERNAL_TYPES.search(return_type):
            continue
        parameters = [
            p for p in split_top_level(arguments)
            if not p.startswith("OUT ")
        ]
        kind_note = {"a": "Aggregate function", "w": "Window function"}.get(kind)
        documentation = doc[:1].upper() + doc[1:] if doc else ""
        if kind_note:
            documentation = f"{documentation}\n\n*{kind_note}*" if documentation else f"*{kind_note}*"
        entries.append({
            "name": name,
            "parameters": parameters,
            "return_type": return_type,
            "documentation": documentation,
        })
    emit("postgres", entries, f"pg_catalog.pg_proc on PostgreSQL {version}")


# ---------------------------------------------------------------------------
# MySQL / MariaDB


def mysql(args):
    query = (
        "SELECT TO_BASE64(t.name), TO_BASE64(t.description), TO_BASE64(COALESCE(t.example, '')), "
        "TO_BASE64(c.name) FROM mysql.help_topic t "
        "JOIN mysql.help_category c ON c.help_category_id = t.help_category_id"
    )
    rows = subprocess.run(
        ["docker", "exec", args.mysql_container, "mariadb", f"-u{args.mysql_user}",
         f"-p{args.mysql_password}", "-N", "-B", "-e", query],
        check=True, capture_output=True, text=True,
    ).stdout
    version = subprocess.run(
        ["docker", "exec", args.mysql_container, "mariadb", f"-u{args.mysql_user}",
         f"-p{args.mysql_password}", "-N", "-B", "-e", "SELECT VERSION()"],
        check=True, capture_output=True, text=True,
    ).stdout.strip()

    def decode(cell):
        return base64.b64decode(cell.replace("\\n", "")).decode("utf-8", errors="replace")

    entries = []
    for line in rows.splitlines():
        if not line.strip():
            continue
        name, description, example, category = (decode(c) for c in line.split("\t"))
        syntax_match = re.search(r"Syntax\n-+\n(.*?)(?:\n\n[A-Z][A-Za-z ]+\n-+\n|\Z)", description, re.S)
        if not syntax_match:
            continue
        syntax_block = syntax_match.group(1).strip()
        body_match = re.search(r"Description\n-+\n(.*)", description, re.S)
        body = body_match.group(1).strip() if body_match else ""
        # The help text is plain text with ASCII result tables; fence the
        # examples so they survive markdown rendering, and link the URL line.
        url = ""
        url_match = re.search(r"\n\s*URL: (\S+)\s*$", body)
        if url_match:
            url = url_match.group(1)
            body = body[: url_match.start()].rstrip()
        example_text = example.strip()
        example_match = re.search(r"\n\s*Examples?\n-+\n", body)
        if example_match:
            example_text = (body[example_match.end():].strip() + "\n\n" + example_text).strip()
            body = body[: example_match.start()].rstrip()
        parts = [f"*{category}*"]
        if body:
            parts.append(body)
        if example_text:
            parts.append(f"```sql\n{example_text}\n```")
        if url:
            parts.append(f"[{url}]({url})")
        documentation = "\n\n".join(parts)

        # A topic can list several forms (`CONCAT(str1,str2,...)`, `SUBSTR(str,pos)`,
        # `SUBSTR(str FROM pos)`); each parseable form becomes an overload.
        forms = [parse_call_syntax(line) for line in syntax_block.splitlines()]
        forms = [f for f in forms if f and f[0].upper() == name.upper()]
        if not forms:
            continue
        for _, parameters in forms:
            entries.append({
                "name": name,
                "parameters": parameters,
                "return_type": "",
                "documentation": documentation,
            })
    emit("mysql", entries, f"mysql.help_topic on MariaDB {version}")


# ---------------------------------------------------------------------------
# ClickHouse


def clickhouse(args):
    def query(sql):
        request = urllib.request.Request(
            f"http://{args.ch_host}:{args.ch_port}/",
            data=sql.encode(),
            headers={"X-ClickHouse-User": args.ch_user, "X-ClickHouse-Key": args.ch_password},
        )
        with urllib.request.urlopen(request, timeout=30) as response:
            return response.read().decode()

    version = query("SELECT version() FORMAT TSVRaw").strip()
    rows = [
        json.loads(line)
        for line in query(
            "SELECT name, is_aggregate, alias_to, description, syntax, arguments, "
            "returned_value, categories FROM system.functions WHERE origin = 'System' "
            "FORMAT JSONEachRow"
        ).splitlines()
        if line.strip()
    ]
    by_name = {row["name"]: row for row in rows}

    entries = []
    for row in rows:
        name = row["name"]
        if name.startswith("_"):
            continue
        source = by_name.get(row["alias_to"]) if row["alias_to"] else row
        source = source or row
        parsed = parse_call_syntax(source["syntax"]) if source["syntax"] else None
        parameters = parsed[1] if parsed else []
        description = trim_paragraphs(source["description"].strip(), 1200)
        parts = []
        if row["alias_to"]:
            parts.append(f"Alias of `{row['alias_to']}`.")
        if description:
            parts.append(description)
        if source["arguments"].strip():
            parts.append("**Arguments**\n\n" + source["arguments"].strip())
        if source["returned_value"].strip():
            parts.append("**Returns** " + source["returned_value"].strip())
        notes = []
        if row["is_aggregate"]:
            notes.append("Aggregate function")
        if source["categories"].strip():
            notes.append(source["categories"].strip())
        if notes:
            parts.append("*" + ", ".join(notes) + "*")
        entries.append({
            "name": name,
            "parameters": parameters,
            "return_type": "",
            "documentation": "\n\n".join(parts),
        })
    emit("clickhouse", entries, f"system.functions on ClickHouse {version}")


# ---------------------------------------------------------------------------
# SQLite (lint only)


def sqlite(args):
    connection = sqlite3.connect(":memory:")
    builtin = {
        row[0].lower()
        for row in connection.execute(
            "SELECT DISTINCT name FROM pragma_function_list WHERE builtin = 1"
        )
    }
    path = os.path.join(OUT_DIR, "sqlite.rs")
    with open(path) as handle:
        curated = set(re.findall(r'name: "([^"]+)"', handle.read()))
    curated = {name.lower() for name in curated}
    missing = sorted(builtin - curated)
    print(f"sqlite {sqlite3.sqlite_version}: {len(builtin)} built-ins, {len(curated)} curated")
    if missing:
        print("missing from sqlite.rs: " + ", ".join(missing))
    unknown = sorted(curated - builtin)
    if unknown:
        print("curated but not reported by pragma_function_list (extensions or SQL-only forms): "
              + ", ".join(unknown))


# ---------------------------------------------------------------------------


def main():
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("dialect", choices=["postgres", "mysql", "clickhouse", "sqlite", "all"])
    parser.add_argument("--pg-host", default="127.0.0.1")
    parser.add_argument("--pg-port", default=5488, type=int)
    parser.add_argument("--pg-user", default="blanco")
    parser.add_argument("--pg-password", default="blanco")
    parser.add_argument("--pg-database", default="blanco")
    parser.add_argument("--mysql-container", default="blanco-mysqltestdb-1")
    parser.add_argument("--mysql-user", default="root")
    parser.add_argument("--mysql-password", default="blanco")
    parser.add_argument("--ch-host", default="127.0.0.1")
    parser.add_argument("--ch-port", default=8124, type=int)
    parser.add_argument("--ch-user", default="blanco")
    parser.add_argument("--ch-password", default="blanco")
    args = parser.parse_args()

    steps = {"postgres": postgres, "mysql": mysql, "clickhouse": clickhouse, "sqlite": sqlite}
    selected = steps.keys() if args.dialect == "all" else [args.dialect]
    failed = False
    for name in selected:
        try:
            steps[name](args)
        except Exception as error:  # report every dialect before failing
            failed = True
            print(f"{name}: failed: {error}", file=sys.stderr)
    sys.exit(1 if failed else 0)


if __name__ == "__main__":
    main()
