// Curated by hand from the T-SQL function reference (learn.microsoft.com/sql/t-sql/functions).
// `scripts/extract-sql-functions.py mssql` never rewrites this file.

use super::FunctionSignature;

#[rustfmt::skip]
pub(super) const FUNCTIONS: &[FunctionSignature] = &[
    FunctionSignature {
        name: "@@ERROR",
        parameters: &[],
        return_type: "int",
        documentation: "*System and Metadata*\n\nError number of the last statement.",
    },
    FunctionSignature {
        name: "@@IDENTITY",
        parameters: &[],
        return_type: "numeric(38,0)",
        documentation: "*System and Metadata*\n\nLast identity value inserted in the session.",
    },
    FunctionSignature {
        name: "@@ROWCOUNT",
        parameters: &[],
        return_type: "int",
        documentation: "*System and Metadata*\n\nRows affected by the last statement.",
    },
    FunctionSignature {
        name: "@@TRANCOUNT",
        parameters: &[],
        return_type: "int",
        documentation: "*System and Metadata*\n\nNumber of BEGIN TRANSACTION statements in the session.",
    },
    FunctionSignature {
        name: "@@VERSION",
        parameters: &[],
        return_type: "nvarchar",
        documentation: "*System and Metadata*\n\nSQL Server version string.",
    },
    FunctionSignature {
        name: "ABS",
        parameters: &["numeric_expression"],
        return_type: "",
        documentation: "*Mathematical*\n\nAbsolute value.",
    },
    FunctionSignature {
        name: "ACOS",
        parameters: &["float_expression"],
        return_type: "float",
        documentation: "*Mathematical*\n\nAngle in radians whose cosine is the argument.",
    },
    FunctionSignature {
        name: "APP_NAME",
        parameters: &[],
        return_type: "nvarchar(128)",
        documentation: "*System and Metadata*\n\nApplication name of the current session.",
    },
    FunctionSignature {
        name: "APPROX_COUNT_DISTINCT",
        parameters: &["expression"],
        return_type: "bigint",
        documentation: "*Aggregate*\n\nApproximate number of distinct non-null values.",
    },
    FunctionSignature {
        name: "APPROX_PERCENTILE_CONT",
        parameters: &["numeric_literal"],
        return_type: "",
        documentation: "*Aggregate*\n\nApproximate interpolated percentile (WITHIN GROUP (ORDER BY ...)).",
    },
    FunctionSignature {
        name: "APPROX_PERCENTILE_DISC",
        parameters: &["numeric_literal"],
        return_type: "",
        documentation: "*Aggregate*\n\nApproximate discrete percentile (WITHIN GROUP (ORDER BY ...)).",
    },
    FunctionSignature {
        name: "ASCII",
        parameters: &["character_expression"],
        return_type: "int",
        documentation: "*String*\n\nASCII code of the leftmost character.",
    },
    FunctionSignature {
        name: "ASIN",
        parameters: &["float_expression"],
        return_type: "float",
        documentation: "*Mathematical*\n\nAngle in radians whose sine is the argument.",
    },
    FunctionSignature {
        name: "ATAN",
        parameters: &["float_expression"],
        return_type: "float",
        documentation: "*Mathematical*\n\nAngle in radians whose tangent is the argument.",
    },
    FunctionSignature {
        name: "ATN2",
        parameters: &["float_expression", "float_expression"],
        return_type: "float",
        documentation: "*Mathematical*\n\nAngle in radians between the positive x-axis and the ray to (x, y).",
    },
    FunctionSignature {
        name: "AVG",
        parameters: &["expression"],
        return_type: "",
        documentation: "*Aggregate*\n\nAverage of the values in the group.",
    },
    FunctionSignature {
        name: "BINARY_CHECKSUM",
        parameters: &["*"],
        return_type: "int",
        documentation: "*System and Metadata*\n\nBinary checksum over the row or expressions.",
    },
    FunctionSignature {
        name: "CAST",
        parameters: &["expression AS data_type"],
        return_type: "",
        documentation: "*Conversion and Logical*\n\nExpression converted to the data type.",
    },
    FunctionSignature {
        name: "CEILING",
        parameters: &["numeric_expression"],
        return_type: "",
        documentation: "*Mathematical*\n\nSmallest integer greater than or equal to the argument.",
    },
    FunctionSignature {
        name: "CERTENCODED",
        parameters: &["cert_ID"],
        return_type: "varbinary",
        documentation: "*System and Metadata*\n\nPublic portion of a certificate.",
    },
    FunctionSignature {
        name: "CHAR",
        parameters: &["integer_expression"],
        return_type: "char(1)",
        documentation: "*String*\n\nCharacter for the ASCII code.",
    },
    FunctionSignature {
        name: "CHARINDEX",
        parameters: &["expressionToFind", "expressionToSearch"],
        return_type: "int",
        documentation: "*String*\n\n1-based start of the first occurrence, or 0.",
    },
    FunctionSignature {
        name: "CHARINDEX",
        parameters: &["expressionToFind", "expressionToSearch", "start_location"],
        return_type: "int",
        documentation: "*String*\n\nStart of the first occurrence at or after start_location.",
    },
    FunctionSignature {
        name: "CHECKSUM",
        parameters: &["*"],
        return_type: "int",
        documentation: "*System and Metadata*\n\nChecksum over the row or expressions.",
    },
    FunctionSignature {
        name: "CHECKSUM_AGG",
        parameters: &["expression"],
        return_type: "int",
        documentation: "*Aggregate*\n\nChecksum of the values in the group.",
    },
    FunctionSignature {
        name: "CHOOSE",
        parameters: &["index", "val_1", "val_2", "..."],
        return_type: "",
        documentation: "*Conversion and Logical*\n\nItem at the given 1-based index.",
    },
    FunctionSignature {
        name: "COALESCE",
        parameters: &["expression", "expression", "..."],
        return_type: "",
        documentation: "*Conversion and Logical*\n\nFirst non-NULL expression.",
    },
    FunctionSignature {
        name: "COL_LENGTH",
        parameters: &["table", "column"],
        return_type: "smallint",
        documentation: "*System and Metadata*\n\nDefined length of a column in bytes.",
    },
    FunctionSignature {
        name: "COL_NAME",
        parameters: &["table_id", "column_id"],
        return_type: "sysname",
        documentation: "*System and Metadata*\n\nName of a column by ids.",
    },
    FunctionSignature {
        name: "COLUMNPROPERTY",
        parameters: &["id", "column", "property"],
        return_type: "int",
        documentation: "*System and Metadata*\n\nInformation about a column or parameter.",
    },
    FunctionSignature {
        name: "COMPRESS",
        parameters: &["expression"],
        return_type: "varbinary(max)",
        documentation: "*System and Metadata*\n\nGZIP-compressed bytes.",
    },
    FunctionSignature {
        name: "CONCAT",
        parameters: &["string_value1", "string_value2", "..."],
        return_type: "string",
        documentation: "*String*\n\nConcatenation of two or more strings; NULLs become empty strings.",
    },
    FunctionSignature {
        name: "CONCAT_WS",
        parameters: &["separator", "argument1", "argument2", "..."],
        return_type: "string",
        documentation: "*String*\n\nConcatenation with a separator, skipping NULLs.",
    },
    FunctionSignature {
        name: "CONNECTIONPROPERTY",
        parameters: &["property"],
        return_type: "",
        documentation: "*System and Metadata*\n\nConnection property of the current request.",
    },
    FunctionSignature {
        name: "CONTEXT_INFO",
        parameters: &[],
        return_type: "varbinary(128)",
        documentation: "*System and Metadata*\n\nContext info set for the session.",
    },
    FunctionSignature {
        name: "CONVERT",
        parameters: &["data_type", "expression"],
        return_type: "",
        documentation: "*Conversion and Logical*\n\nExpression converted to the data type.",
    },
    FunctionSignature {
        name: "CONVERT",
        parameters: &["data_type", "expression", "style"],
        return_type: "",
        documentation: "*Conversion and Logical*\n\nExpression converted using the given style.",
    },
    FunctionSignature {
        name: "COS",
        parameters: &["float_expression"],
        return_type: "float",
        documentation: "*Mathematical*\n\nCosine.",
    },
    FunctionSignature {
        name: "COT",
        parameters: &["float_expression"],
        return_type: "float",
        documentation: "*Mathematical*\n\nCotangent.",
    },
    FunctionSignature {
        name: "COUNT",
        parameters: &["expression"],
        return_type: "int",
        documentation: "*Aggregate*\n\nNumber of items in the group.",
    },
    FunctionSignature {
        name: "COUNT_BIG",
        parameters: &["expression"],
        return_type: "bigint",
        documentation: "*Aggregate*\n\nNumber of items in the group as bigint.",
    },
    FunctionSignature {
        name: "CUME_DIST",
        parameters: &[],
        return_type: "float",
        documentation: "*Analytic and Ranking*\n\nCumulative distribution of a value within a group.",
    },
    FunctionSignature {
        name: "CURRENT_TIMESTAMP",
        parameters: &[],
        return_type: "datetime",
        documentation: "*Date and Time*\n\nCurrent database system timestamp (same as GETDATE()).",
    },
    FunctionSignature {
        name: "CURRENT_USER",
        parameters: &[],
        return_type: "sysname",
        documentation: "*System and Metadata*\n\nName of the current user.",
    },
    FunctionSignature {
        name: "DATALENGTH",
        parameters: &["expression"],
        return_type: "int",
        documentation: "*System and Metadata*\n\nNumber of bytes used to represent the expression.",
    },
    FunctionSignature {
        name: "DATE_BUCKET",
        parameters: &["datepart", "number", "date"],
        return_type: "",
        documentation: "*Date and Time*\n\nStart of the bucket of `number` dateparts the date falls in.",
    },
    FunctionSignature {
        name: "DATE_BUCKET",
        parameters: &["datepart", "number", "date", "origin"],
        return_type: "",
        documentation: "*Date and Time*\n\nBucket start relative to the origin date.",
    },
    FunctionSignature {
        name: "DATEADD",
        parameters: &["datepart", "number", "date"],
        return_type: "",
        documentation: "*Date and Time*\n\nDate with the number of datepart units added.",
    },
    FunctionSignature {
        name: "DATEDIFF",
        parameters: &["datepart", "startdate", "enddate"],
        return_type: "int",
        documentation: "*Date and Time*\n\nCount of datepart boundaries crossed between two dates.",
    },
    FunctionSignature {
        name: "DATEDIFF_BIG",
        parameters: &["datepart", "startdate", "enddate"],
        return_type: "bigint",
        documentation: "*Date and Time*\n\nLike DATEDIFF but returns bigint.",
    },
    FunctionSignature {
        name: "DATEFROMPARTS",
        parameters: &["year", "month", "day"],
        return_type: "date",
        documentation: "*Date and Time*\n\nDate built from its parts.",
    },
    FunctionSignature {
        name: "DATENAME",
        parameters: &["datepart", "date"],
        return_type: "nvarchar",
        documentation: "*Date and Time*\n\nName of the datepart (e.g. month name).",
    },
    FunctionSignature {
        name: "DATEPART",
        parameters: &["datepart", "date"],
        return_type: "int",
        documentation: "*Date and Time*\n\nInteger for the datepart.",
    },
    FunctionSignature {
        name: "DATETIME2FROMPARTS",
        parameters: &["year", "month", "day", "hour", "minute", "seconds", "fractions", "precision"],
        return_type: "datetime2",
        documentation: "*Date and Time*\n\ndatetime2 built from its parts.",
    },
    FunctionSignature {
        name: "DATETIMEFROMPARTS",
        parameters: &["year", "month", "day", "hour", "minute", "seconds", "milliseconds"],
        return_type: "datetime",
        documentation: "*Date and Time*\n\ndatetime built from its parts.",
    },
    FunctionSignature {
        name: "DATETIMEOFFSETFROMPARTS",
        parameters: &["year", "month", "day", "hour", "minute", "seconds", "fractions", "hour_offset", "minute_offset", "precision"],
        return_type: "datetimeoffset",
        documentation: "*Date and Time*\n\ndatetimeoffset built from its parts.",
    },
    FunctionSignature {
        name: "DATETRUNC",
        parameters: &["datepart", "date"],
        return_type: "",
        documentation: "*Date and Time*\n\nDate truncated to the given datepart.",
    },
    FunctionSignature {
        name: "DAY",
        parameters: &["date"],
        return_type: "int",
        documentation: "*Date and Time*\n\nDay of the month.",
    },
    FunctionSignature {
        name: "DB_ID",
        parameters: &[],
        return_type: "int",
        documentation: "*System and Metadata*\n\nId of the current database.",
    },
    FunctionSignature {
        name: "DB_ID",
        parameters: &["database_name"],
        return_type: "int",
        documentation: "*System and Metadata*\n\nId of the named database.",
    },
    FunctionSignature {
        name: "DB_NAME",
        parameters: &[],
        return_type: "nvarchar(128)",
        documentation: "*System and Metadata*\n\nName of the current database.",
    },
    FunctionSignature {
        name: "DB_NAME",
        parameters: &["database_id"],
        return_type: "nvarchar(128)",
        documentation: "*System and Metadata*\n\nName of the database with the id.",
    },
    FunctionSignature {
        name: "DECOMPRESS",
        parameters: &["expression"],
        return_type: "varbinary(max)",
        documentation: "*System and Metadata*\n\nGZIP-decompressed bytes.",
    },
    FunctionSignature {
        name: "DECRYPTBYPASSPHRASE",
        parameters: &["passphrase", "ciphertext"],
        return_type: "varbinary",
        documentation: "*System and Metadata*\n\nData decrypted with a passphrase.",
    },
    FunctionSignature {
        name: "DEGREES",
        parameters: &["numeric_expression"],
        return_type: "",
        documentation: "*Mathematical*\n\nRadians converted to degrees.",
    },
    FunctionSignature {
        name: "DENSE_RANK",
        parameters: &[],
        return_type: "bigint",
        documentation: "*Analytic and Ranking*\n\nRank without gaps.",
    },
    FunctionSignature {
        name: "DIFFERENCE",
        parameters: &["character_expression", "character_expression"],
        return_type: "int",
        documentation: "*String*\n\nDifference (0-4) between the SOUNDEX values of two strings.",
    },
    FunctionSignature {
        name: "ENCRYPTBYPASSPHRASE",
        parameters: &["passphrase", "cleartext"],
        return_type: "varbinary",
        documentation: "*System and Metadata*\n\nData encrypted with a passphrase.",
    },
    FunctionSignature {
        name: "EOMONTH",
        parameters: &["start_date"],
        return_type: "date",
        documentation: "*Date and Time*\n\nLast day of the month.",
    },
    FunctionSignature {
        name: "EOMONTH",
        parameters: &["start_date", "month_to_add"],
        return_type: "date",
        documentation: "*Date and Time*\n\nLast day of the month after adding months.",
    },
    FunctionSignature {
        name: "ERROR_LINE",
        parameters: &[],
        return_type: "int",
        documentation: "*System and Metadata*\n\nLine number of the error in a CATCH block.",
    },
    FunctionSignature {
        name: "ERROR_MESSAGE",
        parameters: &[],
        return_type: "nvarchar(4000)",
        documentation: "*System and Metadata*\n\nMessage text of the error in a CATCH block.",
    },
    FunctionSignature {
        name: "ERROR_NUMBER",
        parameters: &[],
        return_type: "int",
        documentation: "*System and Metadata*\n\nError number in a CATCH block.",
    },
    FunctionSignature {
        name: "ERROR_PROCEDURE",
        parameters: &[],
        return_type: "nvarchar(128)",
        documentation: "*System and Metadata*\n\nProcedure or trigger name in a CATCH block.",
    },
    FunctionSignature {
        name: "ERROR_SEVERITY",
        parameters: &[],
        return_type: "int",
        documentation: "*System and Metadata*\n\nSeverity of the error in a CATCH block.",
    },
    FunctionSignature {
        name: "ERROR_STATE",
        parameters: &[],
        return_type: "int",
        documentation: "*System and Metadata*\n\nState of the error in a CATCH block.",
    },
    FunctionSignature {
        name: "EXP",
        parameters: &["float_expression"],
        return_type: "float",
        documentation: "*Mathematical*\n\nExponential value.",
    },
    FunctionSignature {
        name: "FIRST_VALUE",
        parameters: &["scalar_expression"],
        return_type: "",
        documentation: "*Analytic and Ranking*\n\nFirst value in an ordered set.",
    },
    FunctionSignature {
        name: "FLOOR",
        parameters: &["numeric_expression"],
        return_type: "",
        documentation: "*Mathematical*\n\nLargest integer less than or equal to the argument.",
    },
    FunctionSignature {
        name: "FORMAT",
        parameters: &["value", "format"],
        return_type: "nvarchar",
        documentation: "*String*\n\nValue formatted with a .NET format string.",
    },
    FunctionSignature {
        name: "FORMAT",
        parameters: &["value", "format", "culture"],
        return_type: "nvarchar",
        documentation: "*String*\n\nValue formatted with a .NET format string for the given culture.",
    },
    FunctionSignature {
        name: "FORMATMESSAGE",
        parameters: &["msg_number", "param_value", "..."],
        return_type: "nvarchar",
        documentation: "*System and Metadata*\n\nMessage built from sys.messages.",
    },
    FunctionSignature {
        name: "FORMATMESSAGE",
        parameters: &["msg_string", "param_value", "..."],
        return_type: "nvarchar",
        documentation: "*System and Metadata*\n\nMessage built from a format string.",
    },
    FunctionSignature {
        name: "GENERATE_SERIES",
        parameters: &["start", "stop"],
        return_type: "table",
        documentation: "*System and Metadata*\n\nTable-valued: series of numbers from start to stop.",
    },
    FunctionSignature {
        name: "GENERATE_SERIES",
        parameters: &["start", "stop", "step"],
        return_type: "table",
        documentation: "*System and Metadata*\n\nTable-valued: series with the given step.",
    },
    FunctionSignature {
        name: "GETDATE",
        parameters: &[],
        return_type: "datetime",
        documentation: "*Date and Time*\n\nCurrent database system timestamp.",
    },
    FunctionSignature {
        name: "GETUTCDATE",
        parameters: &[],
        return_type: "datetime",
        documentation: "*Date and Time*\n\nCurrent UTC timestamp.",
    },
    FunctionSignature {
        name: "GREATEST",
        parameters: &["expression1", "expression2", "..."],
        return_type: "",
        documentation: "*System and Metadata*\n\nLargest of the expressions.",
    },
    FunctionSignature {
        name: "GROUPING",
        parameters: &["column_expression"],
        return_type: "tinyint",
        documentation: "*Aggregate*\n\n1 when the column is aggregated by ROLLUP, CUBE or GROUPING SETS.",
    },
    FunctionSignature {
        name: "GROUPING_ID",
        parameters: &["column_expression", "..."],
        return_type: "int",
        documentation: "*Aggregate*\n\nLevel of grouping.",
    },
    FunctionSignature {
        name: "HAS_PERMS_BY_NAME",
        parameters: &["securable", "securable_class", "permission"],
        return_type: "int",
        documentation: "*System and Metadata*\n\n1 if the user has the permission.",
    },
    FunctionSignature {
        name: "HASHBYTES",
        parameters: &["algorithm", "input"],
        return_type: "varbinary(8000)",
        documentation: "*System and Metadata*\n\nHash of the input (MD5, SHA1, SHA2_256, SHA2_512).",
    },
    FunctionSignature {
        name: "HOST_ID",
        parameters: &[],
        return_type: "char(10)",
        documentation: "*System and Metadata*\n\nWorkstation id.",
    },
    FunctionSignature {
        name: "HOST_NAME",
        parameters: &[],
        return_type: "nvarchar(128)",
        documentation: "*System and Metadata*\n\nWorkstation name.",
    },
    FunctionSignature {
        name: "IDENT_CURRENT",
        parameters: &["table_or_view"],
        return_type: "numeric(38,0)",
        documentation: "*System and Metadata*\n\nLast identity value generated for the table.",
    },
    FunctionSignature {
        name: "IDENT_INCR",
        parameters: &["table_or_view"],
        return_type: "numeric",
        documentation: "*System and Metadata*\n\nIncrement of the identity column.",
    },
    FunctionSignature {
        name: "IDENT_SEED",
        parameters: &["table_or_view"],
        return_type: "numeric",
        documentation: "*System and Metadata*\n\nSeed of the identity column.",
    },
    FunctionSignature {
        name: "IIF",
        parameters: &["boolean_expression", "true_value", "false_value"],
        return_type: "",
        documentation: "*Conversion and Logical*\n\nOne of two values depending on the condition.",
    },
    FunctionSignature {
        name: "INDEX_COL",
        parameters: &["table_or_view_name", "index_id", "key_id"],
        return_type: "nvarchar(256)",
        documentation: "*System and Metadata*\n\nIndexed column name.",
    },
    FunctionSignature {
        name: "INDEXPROPERTY",
        parameters: &["object_ID", "index_or_statistics_name", "property"],
        return_type: "int",
        documentation: "*System and Metadata*\n\nProperty of an index or statistics.",
    },
    FunctionSignature {
        name: "IS_MEMBER",
        parameters: &["group | role"],
        return_type: "int",
        documentation: "*System and Metadata*\n\n1 if the current user is a member.",
    },
    FunctionSignature {
        name: "IS_ROLEMEMBER",
        parameters: &["role"],
        return_type: "int",
        documentation: "*System and Metadata*\n\n1 if the principal is a member of the role.",
    },
    FunctionSignature {
        name: "IS_SRVROLEMEMBER",
        parameters: &["role"],
        return_type: "int",
        documentation: "*System and Metadata*\n\n1 if the login is a member of the server role.",
    },
    FunctionSignature {
        name: "ISDATE",
        parameters: &["expression"],
        return_type: "int",
        documentation: "*Date and Time*\n\n1 if the expression is a valid date, time or datetime.",
    },
    FunctionSignature {
        name: "ISJSON",
        parameters: &["expression"],
        return_type: "int",
        documentation: "*JSON*\n\n1 if the string is valid JSON.",
    },
    FunctionSignature {
        name: "ISJSON",
        parameters: &["expression", "json_type_constraint"],
        return_type: "int",
        documentation: "*JSON*\n\n1 if the string is valid JSON of the given type.",
    },
    FunctionSignature {
        name: "ISNULL",
        parameters: &["check_expression", "replacement_value"],
        return_type: "",
        documentation: "*Conversion and Logical*\n\nReplacement when the expression is NULL.",
    },
    FunctionSignature {
        name: "ISNUMERIC",
        parameters: &["expression"],
        return_type: "int",
        documentation: "*System and Metadata*\n\n1 if the expression is a valid numeric type.",
    },
    FunctionSignature {
        name: "JSON_ARRAY",
        parameters: &["value", "..."],
        return_type: "nvarchar(max)",
        documentation: "*JSON*\n\nJSON array from the values.",
    },
    FunctionSignature {
        name: "JSON_ARRAYAGG",
        parameters: &["expression"],
        return_type: "nvarchar(max)",
        documentation: "*JSON*\n\nAggregate: JSON array of the values in the group.",
    },
    FunctionSignature {
        name: "JSON_MODIFY",
        parameters: &["expression", "path", "newValue"],
        return_type: "nvarchar(max)",
        documentation: "*JSON*\n\nJSON with the value at path updated.",
    },
    FunctionSignature {
        name: "JSON_OBJECT",
        parameters: &["key:value", "..."],
        return_type: "nvarchar(max)",
        documentation: "*JSON*\n\nJSON object from key:value pairs.",
    },
    FunctionSignature {
        name: "JSON_OBJECTAGG",
        parameters: &["key:value"],
        return_type: "nvarchar(max)",
        documentation: "*JSON*\n\nAggregate: JSON object of the key:value pairs in the group.",
    },
    FunctionSignature {
        name: "JSON_PATH_EXISTS",
        parameters: &["value_expression", "sql_json_path"],
        return_type: "int",
        documentation: "*JSON*\n\n1 if the path exists in the JSON.",
    },
    FunctionSignature {
        name: "JSON_QUERY",
        parameters: &["expression"],
        return_type: "nvarchar(max)",
        documentation: "*JSON*\n\nObject or array at the root of the JSON.",
    },
    FunctionSignature {
        name: "JSON_QUERY",
        parameters: &["expression", "path"],
        return_type: "nvarchar(max)",
        documentation: "*JSON*\n\nObject or array at the path.",
    },
    FunctionSignature {
        name: "JSON_VALUE",
        parameters: &["expression", "path"],
        return_type: "nvarchar(4000)",
        documentation: "*JSON*\n\nScalar value at the path.",
    },
    FunctionSignature {
        name: "LAG",
        parameters: &["scalar_expression"],
        return_type: "",
        documentation: "*Analytic and Ranking*\n\nValue from the previous row.",
    },
    FunctionSignature {
        name: "LAG",
        parameters: &["scalar_expression", "offset"],
        return_type: "",
        documentation: "*Analytic and Ranking*\n\nValue from the row `offset` rows before.",
    },
    FunctionSignature {
        name: "LAG",
        parameters: &["scalar_expression", "offset", "default"],
        return_type: "",
        documentation: "*Analytic and Ranking*\n\nValue `offset` rows before, or default.",
    },
    FunctionSignature {
        name: "LAST_VALUE",
        parameters: &["scalar_expression"],
        return_type: "",
        documentation: "*Analytic and Ranking*\n\nLast value in an ordered set.",
    },
    FunctionSignature {
        name: "LEAD",
        parameters: &["scalar_expression"],
        return_type: "",
        documentation: "*Analytic and Ranking*\n\nValue from the next row.",
    },
    FunctionSignature {
        name: "LEAD",
        parameters: &["scalar_expression", "offset"],
        return_type: "",
        documentation: "*Analytic and Ranking*\n\nValue from the row `offset` rows after.",
    },
    FunctionSignature {
        name: "LEAD",
        parameters: &["scalar_expression", "offset", "default"],
        return_type: "",
        documentation: "*Analytic and Ranking*\n\nValue `offset` rows after, or default.",
    },
    FunctionSignature {
        name: "LEAST",
        parameters: &["expression1", "expression2", "..."],
        return_type: "",
        documentation: "*System and Metadata*\n\nSmallest of the expressions.",
    },
    FunctionSignature {
        name: "LEFT",
        parameters: &["character_expression", "integer_expression"],
        return_type: "varchar",
        documentation: "*String*\n\nLeft part of a string with the specified number of characters.",
    },
    FunctionSignature {
        name: "LEN",
        parameters: &["string_expression"],
        return_type: "int",
        documentation: "*String*\n\nNumber of characters, excluding trailing spaces.",
    },
    FunctionSignature {
        name: "LOG",
        parameters: &["float_expression"],
        return_type: "float",
        documentation: "*Mathematical*\n\nNatural logarithm.",
    },
    FunctionSignature {
        name: "LOG",
        parameters: &["float_expression", "base"],
        return_type: "float",
        documentation: "*Mathematical*\n\nLogarithm to the given base.",
    },
    FunctionSignature {
        name: "LOG10",
        parameters: &["float_expression"],
        return_type: "float",
        documentation: "*Mathematical*\n\nBase-10 logarithm.",
    },
    FunctionSignature {
        name: "LOWER",
        parameters: &["character_expression"],
        return_type: "varchar",
        documentation: "*String*\n\nString converted to lowercase.",
    },
    FunctionSignature {
        name: "LTRIM",
        parameters: &["character_expression"],
        return_type: "varchar",
        documentation: "*String*\n\nString without leading spaces.",
    },
    FunctionSignature {
        name: "LTRIM",
        parameters: &["character_expression", "characters"],
        return_type: "varchar",
        documentation: "*String*\n\nString without the given leading characters.",
    },
    FunctionSignature {
        name: "MAX",
        parameters: &["expression"],
        return_type: "",
        documentation: "*Aggregate*\n\nMaximum value in the group.",
    },
    FunctionSignature {
        name: "MIN",
        parameters: &["expression"],
        return_type: "",
        documentation: "*Aggregate*\n\nMinimum value in the group.",
    },
    FunctionSignature {
        name: "MONTH",
        parameters: &["date"],
        return_type: "int",
        documentation: "*Date and Time*\n\nMonth of the year.",
    },
    FunctionSignature {
        name: "NCHAR",
        parameters: &["integer_expression"],
        return_type: "nchar(1)",
        documentation: "*String*\n\nUnicode character for the code.",
    },
    FunctionSignature {
        name: "NEWID",
        parameters: &[],
        return_type: "uniqueidentifier",
        documentation: "*System and Metadata*\n\nNew GUID.",
    },
    FunctionSignature {
        name: "NEWSEQUENTIALID",
        parameters: &[],
        return_type: "uniqueidentifier",
        documentation: "*System and Metadata*\n\nGUID greater than any previously generated (DEFAULT constraints only).",
    },
    FunctionSignature {
        name: "NTILE",
        parameters: &["integer_expression"],
        return_type: "bigint",
        documentation: "*Analytic and Ranking*\n\nRows distributed into the given number of groups.",
    },
    FunctionSignature {
        name: "NULLIF",
        parameters: &["expression", "expression"],
        return_type: "",
        documentation: "*Conversion and Logical*\n\nNULL if the two expressions are equal.",
    },
    FunctionSignature {
        name: "OBJECT_DEFINITION",
        parameters: &["object_id"],
        return_type: "nvarchar(max)",
        documentation: "*System and Metadata*\n\nSource text of the module.",
    },
    FunctionSignature {
        name: "OBJECT_ID",
        parameters: &["object_name"],
        return_type: "int",
        documentation: "*System and Metadata*\n\nObject id of a schema-scoped object.",
    },
    FunctionSignature {
        name: "OBJECT_ID",
        parameters: &["object_name", "object_type"],
        return_type: "int",
        documentation: "*System and Metadata*\n\nObject id of an object of the given type.",
    },
    FunctionSignature {
        name: "OBJECT_NAME",
        parameters: &["object_id"],
        return_type: "sysname",
        documentation: "*System and Metadata*\n\nName of the object.",
    },
    FunctionSignature {
        name: "OBJECT_NAME",
        parameters: &["object_id", "database_id"],
        return_type: "sysname",
        documentation: "*System and Metadata*\n\nName of the object in the database.",
    },
    FunctionSignature {
        name: "OBJECT_SCHEMA_NAME",
        parameters: &["object_id"],
        return_type: "sysname",
        documentation: "*System and Metadata*\n\nSchema name of the object.",
    },
    FunctionSignature {
        name: "OBJECTPROPERTY",
        parameters: &["id", "property"],
        return_type: "int",
        documentation: "*System and Metadata*\n\nProperty of a schema-scoped object.",
    },
    FunctionSignature {
        name: "OBJECTPROPERTYEX",
        parameters: &["id", "property"],
        return_type: "sql_variant",
        documentation: "*System and Metadata*\n\nProperty of a schema-scoped object.",
    },
    FunctionSignature {
        name: "OPENJSON",
        parameters: &["jsonExpression"],
        return_type: "table",
        documentation: "*JSON*\n\nTable-valued: key, value and type of each element.",
    },
    FunctionSignature {
        name: "OPENJSON",
        parameters: &["jsonExpression", "path"],
        return_type: "table",
        documentation: "*JSON*\n\nTable-valued: elements at the path (supports WITH (...) schema).",
    },
    FunctionSignature {
        name: "OPENQUERY",
        parameters: &["linked_server", "query"],
        return_type: "table",
        documentation: "*System and Metadata*\n\nTable-valued: pass-through query on a linked server.",
    },
    FunctionSignature {
        name: "OPENROWSET",
        parameters: &["provider_name", "provider_string", "object"],
        return_type: "table",
        documentation: "*System and Metadata*\n\nTable-valued: ad hoc connection to an OLE DB data source.",
    },
    FunctionSignature {
        name: "OPENXML",
        parameters: &["idoc", "rowpattern", "flags"],
        return_type: "table",
        documentation: "*System and Metadata*\n\nTable-valued: rowset over an XML document.",
    },
    FunctionSignature {
        name: "ORIGINAL_LOGIN",
        parameters: &[],
        return_type: "sysname",
        documentation: "*System and Metadata*\n\nLogin that connected to the instance.",
    },
    FunctionSignature {
        name: "PARSE",
        parameters: &["string_value AS data_type"],
        return_type: "",
        documentation: "*Conversion and Logical*\n\nString parsed to the data type using .NET CLR.",
    },
    FunctionSignature {
        name: "PARSE",
        parameters: &["string_value AS data_type USING culture"],
        return_type: "",
        documentation: "*Conversion and Logical*\n\nString parsed with the given culture.",
    },
    FunctionSignature {
        name: "PARSENAME",
        parameters: &["object_name", "object_piece"],
        return_type: "sysname",
        documentation: "*System and Metadata*\n\nPiece (1=object, 2=schema, 3=database, 4=server) of a four-part name.",
    },
    FunctionSignature {
        name: "PATINDEX",
        parameters: &["%pattern%", "expression"],
        return_type: "int",
        documentation: "*String*\n\nStart of the first occurrence of a pattern, or 0.",
    },
    FunctionSignature {
        name: "PERCENT_RANK",
        parameters: &[],
        return_type: "float",
        documentation: "*Analytic and Ranking*\n\nRelative rank of a row within a group.",
    },
    FunctionSignature {
        name: "PERCENTILE_CONT",
        parameters: &["numeric_literal"],
        return_type: "float",
        documentation: "*Analytic and Ranking*\n\nInterpolated percentile (WITHIN GROUP (ORDER BY ...)).",
    },
    FunctionSignature {
        name: "PERCENTILE_DISC",
        parameters: &["numeric_literal"],
        return_type: "",
        documentation: "*Analytic and Ranking*\n\nDiscrete percentile (WITHIN GROUP (ORDER BY ...)).",
    },
    FunctionSignature {
        name: "PI",
        parameters: &[],
        return_type: "float",
        documentation: "*Mathematical*\n\nConstant value of pi.",
    },
    FunctionSignature {
        name: "POWER",
        parameters: &["float_expression", "y"],
        return_type: "",
        documentation: "*Mathematical*\n\nValue raised to the power y.",
    },
    FunctionSignature {
        name: "QUOTENAME",
        parameters: &["character_string"],
        return_type: "nvarchar(258)",
        documentation: "*String*\n\nString as a valid delimited identifier.",
    },
    FunctionSignature {
        name: "QUOTENAME",
        parameters: &["character_string", "quote_character"],
        return_type: "nvarchar(258)",
        documentation: "*String*\n\nString delimited with the given quote character.",
    },
    FunctionSignature {
        name: "RADIANS",
        parameters: &["numeric_expression"],
        return_type: "",
        documentation: "*Mathematical*\n\nDegrees converted to radians.",
    },
    FunctionSignature {
        name: "RAND",
        parameters: &[],
        return_type: "float",
        documentation: "*Mathematical*\n\nPseudo-random float between 0 and 1.",
    },
    FunctionSignature {
        name: "RAND",
        parameters: &["seed"],
        return_type: "float",
        documentation: "*Mathematical*\n\nPseudo-random float from the given seed.",
    },
    FunctionSignature {
        name: "RANK",
        parameters: &[],
        return_type: "bigint",
        documentation: "*Analytic and Ranking*\n\nRank with gaps.",
    },
    FunctionSignature {
        name: "REPLACE",
        parameters: &["string_expression", "string_pattern", "string_replacement"],
        return_type: "string",
        documentation: "*String*\n\nAll occurrences of a pattern replaced.",
    },
    FunctionSignature {
        name: "REPLICATE",
        parameters: &["string_expression", "integer_expression"],
        return_type: "string",
        documentation: "*String*\n\nString repeated the specified number of times.",
    },
    FunctionSignature {
        name: "REVERSE",
        parameters: &["string_expression"],
        return_type: "string",
        documentation: "*String*\n\nString reversed.",
    },
    FunctionSignature {
        name: "RIGHT",
        parameters: &["character_expression", "integer_expression"],
        return_type: "varchar",
        documentation: "*String*\n\nRight part of a string with the specified number of characters.",
    },
    FunctionSignature {
        name: "ROUND",
        parameters: &["numeric_expression", "length"],
        return_type: "",
        documentation: "*Mathematical*\n\nValue rounded to the given length.",
    },
    FunctionSignature {
        name: "ROUND",
        parameters: &["numeric_expression", "length", "function"],
        return_type: "",
        documentation: "*Mathematical*\n\nValue rounded (function 0) or truncated (non-zero) to the given length.",
    },
    FunctionSignature {
        name: "ROW_NUMBER",
        parameters: &[],
        return_type: "bigint",
        documentation: "*Analytic and Ranking*\n\nSequential row number within the partition.",
    },
    FunctionSignature {
        name: "ROWCOUNT_BIG",
        parameters: &[],
        return_type: "bigint",
        documentation: "*System and Metadata*\n\nRows affected by the last statement as bigint.",
    },
    FunctionSignature {
        name: "RTRIM",
        parameters: &["character_expression"],
        return_type: "varchar",
        documentation: "*String*\n\nString without trailing spaces.",
    },
    FunctionSignature {
        name: "RTRIM",
        parameters: &["character_expression", "characters"],
        return_type: "varchar",
        documentation: "*String*\n\nString without the given trailing characters.",
    },
    FunctionSignature {
        name: "SCHEMA_ID",
        parameters: &[],
        return_type: "int",
        documentation: "*System and Metadata*\n\nId of the default schema.",
    },
    FunctionSignature {
        name: "SCHEMA_ID",
        parameters: &["schema_name"],
        return_type: "int",
        documentation: "*System and Metadata*\n\nId of the named schema.",
    },
    FunctionSignature {
        name: "SCHEMA_NAME",
        parameters: &[],
        return_type: "sysname",
        documentation: "*System and Metadata*\n\nName of the default schema.",
    },
    FunctionSignature {
        name: "SCHEMA_NAME",
        parameters: &["schema_id"],
        return_type: "sysname",
        documentation: "*System and Metadata*\n\nName of the schema with the id.",
    },
    FunctionSignature {
        name: "SCOPE_IDENTITY",
        parameters: &[],
        return_type: "numeric(38,0)",
        documentation: "*System and Metadata*\n\nLast identity value inserted in the current scope.",
    },
    FunctionSignature {
        name: "SERVERPROPERTY",
        parameters: &["propertyname"],
        return_type: "sql_variant",
        documentation: "*System and Metadata*\n\nProperty of the server instance.",
    },
    FunctionSignature {
        name: "SESSION_CONTEXT",
        parameters: &["key"],
        return_type: "sql_variant",
        documentation: "*System and Metadata*\n\nValue of the session context key.",
    },
    FunctionSignature {
        name: "SESSION_USER",
        parameters: &[],
        return_type: "nvarchar(128)",
        documentation: "*System and Metadata*\n\nUser name of the current context.",
    },
    FunctionSignature {
        name: "SESSIONPROPERTY",
        parameters: &["option"],
        return_type: "sql_variant",
        documentation: "*System and Metadata*\n\nSET option of the session.",
    },
    FunctionSignature {
        name: "SIGN",
        parameters: &["numeric_expression"],
        return_type: "",
        documentation: "*Mathematical*\n\n-1, 0 or 1.",
    },
    FunctionSignature {
        name: "SIN",
        parameters: &["float_expression"],
        return_type: "float",
        documentation: "*Mathematical*\n\nSine.",
    },
    FunctionSignature {
        name: "SMALLDATETIMEFROMPARTS",
        parameters: &["year", "month", "day", "hour", "minute"],
        return_type: "smalldatetime",
        documentation: "*Date and Time*\n\nsmalldatetime built from its parts.",
    },
    FunctionSignature {
        name: "SOUNDEX",
        parameters: &["character_expression"],
        return_type: "varchar(4)",
        documentation: "*String*\n\nFour-character SOUNDEX code.",
    },
    FunctionSignature {
        name: "SPACE",
        parameters: &["integer_expression"],
        return_type: "varchar",
        documentation: "*String*\n\nString of repeated spaces.",
    },
    FunctionSignature {
        name: "SQL_VARIANT_PROPERTY",
        parameters: &["expression", "property"],
        return_type: "sql_variant",
        documentation: "*System and Metadata*\n\nBase type and other information about a sql_variant value.",
    },
    FunctionSignature {
        name: "SQRT",
        parameters: &["float_expression"],
        return_type: "float",
        documentation: "*Mathematical*\n\nSquare root.",
    },
    FunctionSignature {
        name: "SQUARE",
        parameters: &["float_expression"],
        return_type: "float",
        documentation: "*Mathematical*\n\nSquare.",
    },
    FunctionSignature {
        name: "STATS_DATE",
        parameters: &["object_id", "stats_id"],
        return_type: "datetime",
        documentation: "*System and Metadata*\n\nDate the statistics were last updated.",
    },
    FunctionSignature {
        name: "STDEV",
        parameters: &["expression"],
        return_type: "float",
        documentation: "*Aggregate*\n\nStatistical standard deviation of the group.",
    },
    FunctionSignature {
        name: "STDEVP",
        parameters: &["expression"],
        return_type: "float",
        documentation: "*Aggregate*\n\nPopulation standard deviation of the group.",
    },
    FunctionSignature {
        name: "STR",
        parameters: &["float_expression"],
        return_type: "varchar",
        documentation: "*String*\n\nCharacter data converted from numeric data.",
    },
    FunctionSignature {
        name: "STR",
        parameters: &["float_expression", "length"],
        return_type: "varchar",
        documentation: "*String*\n\nNumeric converted to a string of the given length.",
    },
    FunctionSignature {
        name: "STR",
        parameters: &["float_expression", "length", "decimal"],
        return_type: "varchar",
        documentation: "*String*\n\nNumeric converted to a string with the given length and decimals.",
    },
    FunctionSignature {
        name: "STRING_AGG",
        parameters: &["expression", "separator"],
        return_type: "string",
        documentation: "*String*\n\nAggregate: values concatenated with the separator (supports WITHIN GROUP (ORDER BY ...)).",
    },
    FunctionSignature {
        name: "STRING_ESCAPE",
        parameters: &["text", "type"],
        return_type: "nvarchar",
        documentation: "*String*\n\nSpecial characters escaped, e.g. for 'json'.",
    },
    FunctionSignature {
        name: "STRING_SPLIT",
        parameters: &["string", "separator"],
        return_type: "table",
        documentation: "*String*\n\nTable-valued: one row per substring.",
    },
    FunctionSignature {
        name: "STRING_SPLIT",
        parameters: &["string", "separator", "enable_ordinal"],
        return_type: "table",
        documentation: "*String*\n\nTable-valued: substrings with an ordinal column.",
    },
    FunctionSignature {
        name: "STUFF",
        parameters: &["character_expression", "start", "length", "replaceWith_expression"],
        return_type: "string",
        documentation: "*String*\n\nCharacters deleted and replaced at the given position.",
    },
    FunctionSignature {
        name: "SUBSTRING",
        parameters: &["expression", "start", "length"],
        return_type: "string",
        documentation: "*String*\n\nPart of a character, binary, text or image expression.",
    },
    FunctionSignature {
        name: "SUM",
        parameters: &["expression"],
        return_type: "",
        documentation: "*Aggregate*\n\nSum of the values in the group.",
    },
    FunctionSignature {
        name: "SUSER_ID",
        parameters: &["login"],
        return_type: "int",
        documentation: "*System and Metadata*\n\nLogin id.",
    },
    FunctionSignature {
        name: "SUSER_NAME",
        parameters: &[],
        return_type: "nvarchar(128)",
        documentation: "*System and Metadata*\n\nLogin name of the current login.",
    },
    FunctionSignature {
        name: "SUSER_NAME",
        parameters: &["server_user_id"],
        return_type: "nvarchar(128)",
        documentation: "*System and Metadata*\n\nLogin name for the id.",
    },
    FunctionSignature {
        name: "SUSER_SID",
        parameters: &[],
        return_type: "varbinary(85)",
        documentation: "*System and Metadata*\n\nSID of the current login.",
    },
    FunctionSignature {
        name: "SUSER_SID",
        parameters: &["login"],
        return_type: "varbinary(85)",
        documentation: "*System and Metadata*\n\nSID of the login.",
    },
    FunctionSignature {
        name: "SUSER_SNAME",
        parameters: &[],
        return_type: "nvarchar(128)",
        documentation: "*System and Metadata*\n\nLogin name of the current login.",
    },
    FunctionSignature {
        name: "SUSER_SNAME",
        parameters: &["server_user_sid"],
        return_type: "nvarchar(128)",
        documentation: "*System and Metadata*\n\nLogin name for the SID.",
    },
    FunctionSignature {
        name: "SWITCHOFFSET",
        parameters: &["datetimeoffset_expression", "timezoneoffset_expression"],
        return_type: "datetimeoffset",
        documentation: "*Date and Time*\n\nValue adjusted to a new time zone offset.",
    },
    FunctionSignature {
        name: "SYSDATETIME",
        parameters: &[],
        return_type: "datetime2(7)",
        documentation: "*Date and Time*\n\nCurrent system timestamp as datetime2.",
    },
    FunctionSignature {
        name: "SYSDATETIMEOFFSET",
        parameters: &[],
        return_type: "datetimeoffset(7)",
        documentation: "*Date and Time*\n\nCurrent system timestamp with time zone offset.",
    },
    FunctionSignature {
        name: "SYSTEM_USER",
        parameters: &[],
        return_type: "nvarchar(128)",
        documentation: "*System and Metadata*\n\nLogin name of the current login.",
    },
    FunctionSignature {
        name: "SYSUTCDATETIME",
        parameters: &[],
        return_type: "datetime2(7)",
        documentation: "*Date and Time*\n\nCurrent UTC timestamp as datetime2.",
    },
    FunctionSignature {
        name: "TAN",
        parameters: &["float_expression"],
        return_type: "float",
        documentation: "*Mathematical*\n\nTangent.",
    },
    FunctionSignature {
        name: "TIMEFROMPARTS",
        parameters: &["hour", "minute", "seconds", "fractions", "precision"],
        return_type: "time",
        documentation: "*Date and Time*\n\ntime built from its parts.",
    },
    FunctionSignature {
        name: "TODATETIMEOFFSET",
        parameters: &["expression", "time_zone"],
        return_type: "datetimeoffset",
        documentation: "*Date and Time*\n\ndatetime2 value converted to datetimeoffset in the given time zone.",
    },
    FunctionSignature {
        name: "TRANSLATE",
        parameters: &["inputString", "characters", "translations"],
        return_type: "string",
        documentation: "*String*\n\nEach character in `characters` replaced by the corresponding one in `translations`.",
    },
    FunctionSignature {
        name: "TRIM",
        parameters: &["characters FROM string"],
        return_type: "varchar",
        documentation: "*String*\n\nString without the given leading and trailing characters.",
    },
    FunctionSignature {
        name: "TRIM",
        parameters: &["string"],
        return_type: "varchar",
        documentation: "*String*\n\nString without leading and trailing spaces.",
    },
    FunctionSignature {
        name: "TRY_CAST",
        parameters: &["expression AS data_type"],
        return_type: "",
        documentation: "*Conversion and Logical*\n\nCAST that returns NULL on failure.",
    },
    FunctionSignature {
        name: "TRY_CONVERT",
        parameters: &["data_type", "expression"],
        return_type: "",
        documentation: "*Conversion and Logical*\n\nCONVERT that returns NULL on failure.",
    },
    FunctionSignature {
        name: "TRY_CONVERT",
        parameters: &["data_type", "expression", "style"],
        return_type: "",
        documentation: "*Conversion and Logical*\n\nCONVERT with style that returns NULL on failure.",
    },
    FunctionSignature {
        name: "TRY_PARSE",
        parameters: &["string_value AS data_type"],
        return_type: "",
        documentation: "*Conversion and Logical*\n\nPARSE that returns NULL on failure.",
    },
    FunctionSignature {
        name: "TYPE_ID",
        parameters: &["type_name"],
        return_type: "int",
        documentation: "*System and Metadata*\n\nId of the type.",
    },
    FunctionSignature {
        name: "TYPE_NAME",
        parameters: &["type_id"],
        return_type: "sysname",
        documentation: "*System and Metadata*\n\nName of the type.",
    },
    FunctionSignature {
        name: "TYPEPROPERTY",
        parameters: &["type", "property"],
        return_type: "int",
        documentation: "*System and Metadata*\n\nProperty of a data type.",
    },
    FunctionSignature {
        name: "UNICODE",
        parameters: &["ncharacter_expression"],
        return_type: "int",
        documentation: "*String*\n\nUnicode code point of the first character.",
    },
    FunctionSignature {
        name: "UPPER",
        parameters: &["character_expression"],
        return_type: "varchar",
        documentation: "*String*\n\nString converted to uppercase.",
    },
    FunctionSignature {
        name: "USER_ID",
        parameters: &[],
        return_type: "int",
        documentation: "*System and Metadata*\n\nId of the current user.",
    },
    FunctionSignature {
        name: "USER_ID",
        parameters: &["user"],
        return_type: "int",
        documentation: "*System and Metadata*\n\nId of the user.",
    },
    FunctionSignature {
        name: "USER_NAME",
        parameters: &[],
        return_type: "nvarchar(128)",
        documentation: "*System and Metadata*\n\nName of the current user.",
    },
    FunctionSignature {
        name: "USER_NAME",
        parameters: &["id"],
        return_type: "nvarchar(128)",
        documentation: "*System and Metadata*\n\nName of the user with the id.",
    },
    FunctionSignature {
        name: "VAR",
        parameters: &["expression"],
        return_type: "float",
        documentation: "*Aggregate*\n\nStatistical variance of the group.",
    },
    FunctionSignature {
        name: "VARP",
        parameters: &["expression"],
        return_type: "float",
        documentation: "*Aggregate*\n\nPopulation variance of the group.",
    },
    FunctionSignature {
        name: "XACT_STATE",
        parameters: &[],
        return_type: "smallint",
        documentation: "*System and Metadata*\n\nTransaction state of the session: 1 active, 0 none, -1 uncommittable.",
    },
    FunctionSignature {
        name: "YEAR",
        parameters: &["date"],
        return_type: "int",
        documentation: "*Date and Time*\n\nYear.",
    },
];
