// Curated by hand from the SQLite documentation (lang_corefunc, lang_aggfunc, lang_datefunc, lang_mathfunc, json1, windowfunctions).
// `scripts/extract-sql-functions.py sqlite` never rewrites this file;
// it only lints it against `pragma_function_list`.

use super::FunctionSignature;

#[rustfmt::skip]
pub(super) const FUNCTIONS: &[FunctionSignature] = &[
    FunctionSignature {
        name: "abs",
        parameters: &["X"],
        return_type: "",
        documentation: "*Core*\n\nAbsolute value of X. NULL for NULL, error on integer overflow.",
    },
    FunctionSignature {
        name: "acos",
        parameters: &["X"],
        return_type: "real",
        documentation: "*Math*\n\nArccosine of X, in radians.",
    },
    FunctionSignature {
        name: "acosh",
        parameters: &["X"],
        return_type: "real",
        documentation: "*Math*\n\nHyperbolic arccosine of X.",
    },
    FunctionSignature {
        name: "asin",
        parameters: &["X"],
        return_type: "real",
        documentation: "*Math*\n\nArcsine of X, in radians.",
    },
    FunctionSignature {
        name: "asinh",
        parameters: &["X"],
        return_type: "real",
        documentation: "*Math*\n\nHyperbolic arcsine of X.",
    },
    FunctionSignature {
        name: "atan",
        parameters: &["X"],
        return_type: "real",
        documentation: "*Math*\n\nArctangent of X, in radians.",
    },
    FunctionSignature {
        name: "atan2",
        parameters: &["Y", "X"],
        return_type: "real",
        documentation: "*Math*\n\nArctangent of Y/X, in radians.",
    },
    FunctionSignature {
        name: "atanh",
        parameters: &["X"],
        return_type: "real",
        documentation: "*Math*\n\nHyperbolic arctangent of X.",
    },
    FunctionSignature {
        name: "avg",
        parameters: &["X"],
        return_type: "real",
        documentation: "*Aggregate*\n\nAverage of all non-NULL X in the group.",
    },
    FunctionSignature {
        name: "bm25",
        parameters: &["table", "..."],
        return_type: "real",
        documentation: "*Extension*\n\nFTS5: BM25 relevance score (lower is better).",
    },
    FunctionSignature {
        name: "ceil",
        parameters: &["X"],
        return_type: "integer",
        documentation: "*Math*\n\nSmallest integer not less than X.",
    },
    FunctionSignature {
        name: "ceiling",
        parameters: &["X"],
        return_type: "integer",
        documentation: "*Math*\n\nSmallest integer not less than X.",
    },
    FunctionSignature {
        name: "changes",
        parameters: &[],
        return_type: "integer",
        documentation: "*Core*\n\nNumber of rows modified by the most recent INSERT, UPDATE or DELETE.",
    },
    FunctionSignature {
        name: "char",
        parameters: &["X1", "X2", "..."],
        return_type: "text",
        documentation: "*Core*\n\nString of the characters with the given unicode code points.",
    },
    FunctionSignature {
        name: "coalesce",
        parameters: &["X", "Y", "..."],
        return_type: "",
        documentation: "*Core*\n\nFirst non-NULL argument, or NULL if all are NULL.",
    },
    FunctionSignature {
        name: "concat",
        parameters: &["X", "..."],
        return_type: "text",
        documentation: "*Core*\n\nConcatenation of all non-NULL arguments.",
    },
    FunctionSignature {
        name: "concat_ws",
        parameters: &["SEP", "X", "..."],
        return_type: "text",
        documentation: "*Core*\n\nConcatenation of all non-NULL arguments after the separator, joined by SEP.",
    },
    FunctionSignature {
        name: "cos",
        parameters: &["X"],
        return_type: "real",
        documentation: "*Math*\n\nCosine of X (radians).",
    },
    FunctionSignature {
        name: "cosh",
        parameters: &["X"],
        return_type: "real",
        documentation: "*Math*\n\nHyperbolic cosine of X.",
    },
    FunctionSignature {
        name: "count",
        parameters: &[],
        return_type: "integer",
        documentation: "*Aggregate*\n\nNumber of rows in the group (count(*)).",
    },
    FunctionSignature {
        name: "count",
        parameters: &["X"],
        return_type: "integer",
        documentation: "*Aggregate*\n\nNumber of non-NULL X in the group.",
    },
    FunctionSignature {
        name: "cume_dist",
        parameters: &[],
        return_type: "real",
        documentation: "*Window*\n\nCumulative distribution: (peers before and including) / partition rows.",
    },
    FunctionSignature {
        name: "date",
        parameters: &["time-value", "modifier", "..."],
        return_type: "text",
        documentation: "*Date and Time*\n\nDate as YYYY-MM-DD.",
    },
    FunctionSignature {
        name: "datetime",
        parameters: &["time-value", "modifier", "..."],
        return_type: "text",
        documentation: "*Date and Time*\n\nDate and time as YYYY-MM-DD HH:MM:SS.",
    },
    FunctionSignature {
        name: "degrees",
        parameters: &["X"],
        return_type: "real",
        documentation: "*Math*\n\nX converted from radians to degrees.",
    },
    FunctionSignature {
        name: "dense_rank",
        parameters: &[],
        return_type: "integer",
        documentation: "*Window*\n\nRank without gaps.",
    },
    FunctionSignature {
        name: "exp",
        parameters: &["X"],
        return_type: "real",
        documentation: "*Math*\n\ne raised to the power X.",
    },
    FunctionSignature {
        name: "first_value",
        parameters: &["expr"],
        return_type: "",
        documentation: "*Window*\n\nValue of expr on the first row of the window frame.",
    },
    FunctionSignature {
        name: "floor",
        parameters: &["X"],
        return_type: "integer",
        documentation: "*Math*\n\nLargest integer not greater than X.",
    },
    FunctionSignature {
        name: "format",
        parameters: &["FORMAT", "..."],
        return_type: "text",
        documentation: "*Core*\n\nprintf-style formatting of the arguments.",
    },
    FunctionSignature {
        name: "fts3_tokenizer",
        parameters: &["name"],
        return_type: "blob",
        documentation: "*Extension*\n\nFTS3: pointer to the named tokenizer.",
    },
    FunctionSignature {
        name: "fts5",
        parameters: &["..."],
        return_type: "",
        documentation: "*Extension*\n\nFTS5 auxiliary entry point.",
    },
    FunctionSignature {
        name: "glob",
        parameters: &["X", "Y"],
        return_type: "integer",
        documentation: "*Core*\n\nTrue if string Y matches GLOB pattern X (case sensitive).",
    },
    FunctionSignature {
        name: "group_concat",
        parameters: &["X"],
        return_type: "text",
        documentation: "*Aggregate*\n\nAll non-NULL X concatenated with commas.",
    },
    FunctionSignature {
        name: "group_concat",
        parameters: &["X", "Y"],
        return_type: "text",
        documentation: "*Aggregate*\n\nAll non-NULL X concatenated with separator Y.",
    },
    FunctionSignature {
        name: "hex",
        parameters: &["X"],
        return_type: "text",
        documentation: "*Core*\n\nUppercase hexadecimal rendering of the BLOB X.",
    },
    FunctionSignature {
        name: "highlight",
        parameters: &["table", "column", "open", "close"],
        return_type: "text",
        documentation: "*Extension*\n\nFTS5: column text with matches wrapped in open/close.",
    },
    FunctionSignature {
        name: "if",
        parameters: &["X", "Y", "Z"],
        return_type: "",
        documentation: "*Core*\n\nY if X is true, otherwise Z (alias of iif).",
    },
    FunctionSignature {
        name: "ifnull",
        parameters: &["X", "Y"],
        return_type: "",
        documentation: "*Core*\n\nX if not NULL, otherwise Y.",
    },
    FunctionSignature {
        name: "iif",
        parameters: &["X", "Y", "Z"],
        return_type: "",
        documentation: "*Core*\n\nY if X is true, otherwise Z.",
    },
    FunctionSignature {
        name: "instr",
        parameters: &["X", "Y"],
        return_type: "integer",
        documentation: "*Core*\n\n1-based position of the first occurrence of Y in X, or 0.",
    },
    FunctionSignature {
        name: "json",
        parameters: &["X"],
        return_type: "text",
        documentation: "*JSON*\n\nMinified, validated JSON text of X.",
    },
    FunctionSignature {
        name: "json_array",
        parameters: &["value1", "value2", "..."],
        return_type: "text",
        documentation: "*JSON*\n\nJSON array holding the arguments.",
    },
    FunctionSignature {
        name: "json_array_length",
        parameters: &["json"],
        return_type: "integer",
        documentation: "*JSON*\n\nNumber of elements in the top-level JSON array.",
    },
    FunctionSignature {
        name: "json_array_length",
        parameters: &["json", "path"],
        return_type: "integer",
        documentation: "*JSON*\n\nNumber of elements in the array at path.",
    },
    FunctionSignature {
        name: "json_each",
        parameters: &["json"],
        return_type: "table",
        documentation: "*JSON*\n\nTable-valued: one row per element of the top-level array or object.",
    },
    FunctionSignature {
        name: "json_each",
        parameters: &["json", "path"],
        return_type: "table",
        documentation: "*JSON*\n\nTable-valued: one row per element of the array or object at path.",
    },
    FunctionSignature {
        name: "json_error_position",
        parameters: &["json"],
        return_type: "integer",
        documentation: "*JSON*\n\nCharacter position of the first syntax error, or 0 if well formed.",
    },
    FunctionSignature {
        name: "json_extract",
        parameters: &["json", "path", "..."],
        return_type: "",
        documentation: "*JSON*\n\nValue(s) at the given path(s); several paths yield a JSON array.",
    },
    FunctionSignature {
        name: "json_group_array",
        parameters: &["value"],
        return_type: "text",
        documentation: "*JSON*\n\nAggregate: JSON array of all values in the group.",
    },
    FunctionSignature {
        name: "json_group_object",
        parameters: &["label", "value"],
        return_type: "text",
        documentation: "*JSON*\n\nAggregate: JSON object of all label/value pairs in the group.",
    },
    FunctionSignature {
        name: "json_insert",
        parameters: &["json", "path", "value", "..."],
        return_type: "text",
        documentation: "*JSON*\n\nInsert value(s) at path(s) that do not already exist.",
    },
    FunctionSignature {
        name: "json_object",
        parameters: &["label1", "value1", "..."],
        return_type: "text",
        documentation: "*JSON*\n\nJSON object from label/value pairs.",
    },
    FunctionSignature {
        name: "json_patch",
        parameters: &["json1", "json2"],
        return_type: "text",
        documentation: "*JSON*\n\nRFC 7396 MergePatch of json2 applied to json1.",
    },
    FunctionSignature {
        name: "json_pretty",
        parameters: &["json"],
        return_type: "text",
        documentation: "*JSON*\n\nPretty-printed JSON text.",
    },
    FunctionSignature {
        name: "json_pretty",
        parameters: &["json", "indent"],
        return_type: "text",
        documentation: "*JSON*\n\nPretty-printed JSON text using the given indent string.",
    },
    FunctionSignature {
        name: "json_quote",
        parameters: &["value"],
        return_type: "text",
        documentation: "*JSON*\n\nSQL value converted to its JSON representation.",
    },
    FunctionSignature {
        name: "json_remove",
        parameters: &["json", "path", "..."],
        return_type: "text",
        documentation: "*JSON*\n\nJSON with the elements at path(s) removed.",
    },
    FunctionSignature {
        name: "json_replace",
        parameters: &["json", "path", "value", "..."],
        return_type: "text",
        documentation: "*JSON*\n\nReplace value(s) at path(s) that already exist.",
    },
    FunctionSignature {
        name: "json_set",
        parameters: &["json", "path", "value", "..."],
        return_type: "text",
        documentation: "*JSON*\n\nInsert or replace value(s) at path(s).",
    },
    FunctionSignature {
        name: "json_tree",
        parameters: &["json"],
        return_type: "table",
        documentation: "*JSON*\n\nTable-valued: recursive walk of every element.",
    },
    FunctionSignature {
        name: "json_tree",
        parameters: &["json", "path"],
        return_type: "table",
        documentation: "*JSON*\n\nTable-valued: recursive walk of the element at path.",
    },
    FunctionSignature {
        name: "json_type",
        parameters: &["json"],
        return_type: "text",
        documentation: "*JSON*\n\nType of the top-level JSON value: null, true, false, integer, real, text, array or object.",
    },
    FunctionSignature {
        name: "json_type",
        parameters: &["json", "path"],
        return_type: "text",
        documentation: "*JSON*\n\nType of the value at path.",
    },
    FunctionSignature {
        name: "json_valid",
        parameters: &["json"],
        return_type: "integer",
        documentation: "*JSON*\n\n1 if json is well formed RFC 8259 JSON text.",
    },
    FunctionSignature {
        name: "json_valid",
        parameters: &["json", "flags"],
        return_type: "integer",
        documentation: "*JSON*\n\n1 if json is well formed according to the flags bitmask.",
    },
    FunctionSignature {
        name: "jsonb",
        parameters: &["X"],
        return_type: "blob",
        documentation: "*JSON*\n\nBinary JSONB encoding of X.",
    },
    FunctionSignature {
        name: "jsonb_array",
        parameters: &["value1", "value2", "..."],
        return_type: "blob",
        documentation: "*JSON*\n\nJSONB array holding the arguments.",
    },
    FunctionSignature {
        name: "jsonb_extract",
        parameters: &["json", "path", "..."],
        return_type: "",
        documentation: "*JSON*\n\nLike json_extract() but returns JSONB for objects and arrays.",
    },
    FunctionSignature {
        name: "jsonb_group_array",
        parameters: &["value"],
        return_type: "blob",
        documentation: "*JSON*\n\nAggregate: JSONB array of all values in the group.",
    },
    FunctionSignature {
        name: "jsonb_group_object",
        parameters: &["label", "value"],
        return_type: "blob",
        documentation: "*JSON*\n\nAggregate: JSONB object of all label/value pairs in the group.",
    },
    FunctionSignature {
        name: "jsonb_insert",
        parameters: &["json", "path", "value", "..."],
        return_type: "blob",
        documentation: "*JSON*\n\nJSONB variant of json_insert().",
    },
    FunctionSignature {
        name: "jsonb_object",
        parameters: &["label1", "value1", "..."],
        return_type: "blob",
        documentation: "*JSON*\n\nJSONB object from label/value pairs.",
    },
    FunctionSignature {
        name: "jsonb_patch",
        parameters: &["json1", "json2"],
        return_type: "blob",
        documentation: "*JSON*\n\nJSONB variant of json_patch().",
    },
    FunctionSignature {
        name: "jsonb_remove",
        parameters: &["json", "path", "..."],
        return_type: "blob",
        documentation: "*JSON*\n\nJSONB variant of json_remove().",
    },
    FunctionSignature {
        name: "jsonb_replace",
        parameters: &["json", "path", "value", "..."],
        return_type: "blob",
        documentation: "*JSON*\n\nJSONB variant of json_replace().",
    },
    FunctionSignature {
        name: "jsonb_set",
        parameters: &["json", "path", "value", "..."],
        return_type: "blob",
        documentation: "*JSON*\n\nJSONB variant of json_set().",
    },
    FunctionSignature {
        name: "julianday",
        parameters: &["time-value", "modifier", "..."],
        return_type: "real",
        documentation: "*Date and Time*\n\nJulian day number (fractional days since noon in Greenwich on November 24, 4714 B.C.).",
    },
    FunctionSignature {
        name: "lag",
        parameters: &["expr"],
        return_type: "",
        documentation: "*Window*\n\nValue of expr on the previous row in the partition.",
    },
    FunctionSignature {
        name: "lag",
        parameters: &["expr", "offset"],
        return_type: "",
        documentation: "*Window*\n\nValue of expr on the row `offset` rows before.",
    },
    FunctionSignature {
        name: "lag",
        parameters: &["expr", "offset", "default"],
        return_type: "",
        documentation: "*Window*\n\nValue of expr `offset` rows before, or default.",
    },
    FunctionSignature {
        name: "last_insert_rowid",
        parameters: &[],
        return_type: "integer",
        documentation: "*Core*\n\nROWID of the most recent successful INSERT.",
    },
    FunctionSignature {
        name: "last_value",
        parameters: &["expr"],
        return_type: "",
        documentation: "*Window*\n\nValue of expr on the last row of the window frame.",
    },
    FunctionSignature {
        name: "lead",
        parameters: &["expr"],
        return_type: "",
        documentation: "*Window*\n\nValue of expr on the next row in the partition.",
    },
    FunctionSignature {
        name: "lead",
        parameters: &["expr", "offset"],
        return_type: "",
        documentation: "*Window*\n\nValue of expr on the row `offset` rows after.",
    },
    FunctionSignature {
        name: "lead",
        parameters: &["expr", "offset", "default"],
        return_type: "",
        documentation: "*Window*\n\nValue of expr `offset` rows after, or default.",
    },
    FunctionSignature {
        name: "length",
        parameters: &["X"],
        return_type: "integer",
        documentation: "*Core*\n\nNumber of characters in string X, or bytes in BLOB X.",
    },
    FunctionSignature {
        name: "like",
        parameters: &["X", "Y"],
        return_type: "integer",
        documentation: "*Core*\n\nTrue if Y matches LIKE pattern X.",
    },
    FunctionSignature {
        name: "like",
        parameters: &["X", "Y", "Z"],
        return_type: "integer",
        documentation: "*Core*\n\nTrue if Y matches LIKE pattern X with escape character Z.",
    },
    FunctionSignature {
        name: "likelihood",
        parameters: &["X", "Y"],
        return_type: "",
        documentation: "*Core*\n\nReturns X; hints the planner that X is true with probability Y.",
    },
    FunctionSignature {
        name: "likely",
        parameters: &["X"],
        return_type: "",
        documentation: "*Core*\n\nReturns X; hints the planner that X is usually true.",
    },
    FunctionSignature {
        name: "ln",
        parameters: &["X"],
        return_type: "real",
        documentation: "*Math*\n\nNatural logarithm of X.",
    },
    FunctionSignature {
        name: "load_extension",
        parameters: &["X"],
        return_type: "",
        documentation: "*Core*\n\nLoads the SQLite extension library X.",
    },
    FunctionSignature {
        name: "load_extension",
        parameters: &["X", "Y"],
        return_type: "",
        documentation: "*Core*\n\nLoads extension X using entry point Y.",
    },
    FunctionSignature {
        name: "log",
        parameters: &["X"],
        return_type: "real",
        documentation: "*Math*\n\nBase-10 logarithm of X.",
    },
    FunctionSignature {
        name: "log",
        parameters: &["B", "X"],
        return_type: "real",
        documentation: "*Math*\n\nBase-B logarithm of X.",
    },
    FunctionSignature {
        name: "log10",
        parameters: &["X"],
        return_type: "real",
        documentation: "*Math*\n\nBase-10 logarithm of X.",
    },
    FunctionSignature {
        name: "log2",
        parameters: &["X"],
        return_type: "real",
        documentation: "*Math*\n\nBase-2 logarithm of X.",
    },
    FunctionSignature {
        name: "lower",
        parameters: &["X"],
        return_type: "text",
        documentation: "*Core*\n\nX with ASCII characters converted to lower case.",
    },
    FunctionSignature {
        name: "ltrim",
        parameters: &["X"],
        return_type: "text",
        documentation: "*Core*\n\nX with leading spaces removed.",
    },
    FunctionSignature {
        name: "ltrim",
        parameters: &["X", "Y"],
        return_type: "text",
        documentation: "*Core*\n\nX with leading characters in Y removed.",
    },
    FunctionSignature {
        name: "matchinfo",
        parameters: &["table"],
        return_type: "blob",
        documentation: "*Extension*\n\nFTS3/4: match information blob for the current row.",
    },
    FunctionSignature {
        name: "matchinfo",
        parameters: &["table", "format"],
        return_type: "blob",
        documentation: "*Extension*\n\nFTS3/4: match information blob in the given format.",
    },
    FunctionSignature {
        name: "max",
        parameters: &["X"],
        return_type: "",
        documentation: "*Aggregate*\n\nMaximum of all X in the group.",
    },
    FunctionSignature {
        name: "max",
        parameters: &["X", "Y", "..."],
        return_type: "",
        documentation: "*Core*\n\nLargest argument (with two or more arguments).",
    },
    FunctionSignature {
        name: "min",
        parameters: &["X"],
        return_type: "",
        documentation: "*Aggregate*\n\nMinimum of all non-NULL X in the group.",
    },
    FunctionSignature {
        name: "min",
        parameters: &["X", "Y", "..."],
        return_type: "",
        documentation: "*Core*\n\nSmallest argument (with two or more arguments).",
    },
    FunctionSignature {
        name: "mod",
        parameters: &["X", "Y"],
        return_type: "real",
        documentation: "*Math*\n\nRemainder of X divided by Y.",
    },
    FunctionSignature {
        name: "nth_value",
        parameters: &["expr", "N"],
        return_type: "",
        documentation: "*Window*\n\nValue of expr on the N-th row of the window frame.",
    },
    FunctionSignature {
        name: "ntile",
        parameters: &["N"],
        return_type: "integer",
        documentation: "*Window*\n\nPartition split into N groups, returning the group number.",
    },
    FunctionSignature {
        name: "nullif",
        parameters: &["X", "Y"],
        return_type: "",
        documentation: "*Core*\n\nX if X differs from Y, otherwise NULL.",
    },
    FunctionSignature {
        name: "octet_length",
        parameters: &["X"],
        return_type: "integer",
        documentation: "*Core*\n\nNumber of bytes in the encoding of X.",
    },
    FunctionSignature {
        name: "offsets",
        parameters: &["table"],
        return_type: "text",
        documentation: "*Extension*\n\nFTS3/4: term offsets of the current match.",
    },
    FunctionSignature {
        name: "optimize",
        parameters: &["table"],
        return_type: "text",
        documentation: "*Extension*\n\nFTS3/4: merge all b-tree segments.",
    },
    FunctionSignature {
        name: "percent_rank",
        parameters: &[],
        return_type: "real",
        documentation: "*Window*\n\n(rank - 1) / (partition rows - 1).",
    },
    FunctionSignature {
        name: "pi",
        parameters: &[],
        return_type: "real",
        documentation: "*Math*\n\nApproximate value of π.",
    },
    FunctionSignature {
        name: "pow",
        parameters: &["X", "Y"],
        return_type: "real",
        documentation: "*Math*\n\nX raised to the power Y.",
    },
    FunctionSignature {
        name: "power",
        parameters: &["X", "Y"],
        return_type: "real",
        documentation: "*Math*\n\nX raised to the power Y.",
    },
    FunctionSignature {
        name: "printf",
        parameters: &["FORMAT", "..."],
        return_type: "text",
        documentation: "*Core*\n\nAlias of format().",
    },
    FunctionSignature {
        name: "quote",
        parameters: &["X"],
        return_type: "text",
        documentation: "*Core*\n\nX as an SQL literal suitable for inclusion in a statement.",
    },
    FunctionSignature {
        name: "radians",
        parameters: &["X"],
        return_type: "real",
        documentation: "*Math*\n\nX converted from degrees to radians.",
    },
    FunctionSignature {
        name: "random",
        parameters: &[],
        return_type: "integer",
        documentation: "*Core*\n\nPseudo-random integer between -9223372036854775808 and +9223372036854775807.",
    },
    FunctionSignature {
        name: "randomblob",
        parameters: &["N"],
        return_type: "blob",
        documentation: "*Core*\n\nN-byte BLOB of pseudo-random bytes.",
    },
    FunctionSignature {
        name: "rank",
        parameters: &[],
        return_type: "integer",
        documentation: "*Window*\n\nrow_number() of the first peer in each group, leaving gaps.",
    },
    FunctionSignature {
        name: "replace",
        parameters: &["X", "Y", "Z"],
        return_type: "text",
        documentation: "*Core*\n\nX with every occurrence of Y replaced by Z.",
    },
    FunctionSignature {
        name: "round",
        parameters: &["X"],
        return_type: "real",
        documentation: "*Core*\n\nX rounded to the nearest integer.",
    },
    FunctionSignature {
        name: "round",
        parameters: &["X", "Y"],
        return_type: "real",
        documentation: "*Core*\n\nX rounded to Y digits to the right of the decimal point.",
    },
    FunctionSignature {
        name: "row_number",
        parameters: &[],
        return_type: "integer",
        documentation: "*Window*\n\nNumber of the row within its partition, starting at 1.",
    },
    FunctionSignature {
        name: "rtreecheck",
        parameters: &["db", "table"],
        return_type: "text",
        documentation: "*Extension*\n\nR*Tree: integrity check of the virtual table.",
    },
    FunctionSignature {
        name: "rtreedepth",
        parameters: &["node"],
        return_type: "integer",
        documentation: "*Extension*\n\nR*Tree: depth of the node blob.",
    },
    FunctionSignature {
        name: "rtreenode",
        parameters: &["dimensions", "node"],
        return_type: "text",
        documentation: "*Extension*\n\nR*Tree: decoded node blob.",
    },
    FunctionSignature {
        name: "rtrim",
        parameters: &["X"],
        return_type: "text",
        documentation: "*Core*\n\nX with trailing spaces removed.",
    },
    FunctionSignature {
        name: "rtrim",
        parameters: &["X", "Y"],
        return_type: "text",
        documentation: "*Core*\n\nX with trailing characters in Y removed.",
    },
    FunctionSignature {
        name: "sign",
        parameters: &["X"],
        return_type: "integer",
        documentation: "*Core*\n\n-1, 0 or +1 for negative, zero or positive X; NULL for non-numeric.",
    },
    FunctionSignature {
        name: "sin",
        parameters: &["X"],
        return_type: "real",
        documentation: "*Math*\n\nSine of X (radians).",
    },
    FunctionSignature {
        name: "sinh",
        parameters: &["X"],
        return_type: "real",
        documentation: "*Math*\n\nHyperbolic sine of X.",
    },
    FunctionSignature {
        name: "snippet",
        parameters: &["table"],
        return_type: "text",
        documentation: "*Extension*\n\nFTS3/4: snippet of the current match.",
    },
    FunctionSignature {
        name: "snippet",
        parameters: &["table", "column", "open", "close", "ellipsis", "tokens"],
        return_type: "text",
        documentation: "*Extension*\n\nFTS5: short fragment of column text around a match.",
    },
    FunctionSignature {
        name: "soundex",
        parameters: &["X"],
        return_type: "text",
        documentation: "*Core*\n\nSoundex encoding of X (when compiled with SQLITE_SOUNDEX).",
    },
    FunctionSignature {
        name: "sqlite_compileoption_get",
        parameters: &["N"],
        return_type: "text",
        documentation: "*Core*\n\nN-th compile-time option used to build SQLite.",
    },
    FunctionSignature {
        name: "sqlite_compileoption_used",
        parameters: &["X"],
        return_type: "integer",
        documentation: "*Core*\n\nTrue if compile-time option X was used.",
    },
    FunctionSignature {
        name: "sqlite_offset",
        parameters: &["X"],
        return_type: "integer",
        documentation: "*Core*\n\nByte offset in the database file of the record holding X.",
    },
    FunctionSignature {
        name: "sqlite_source_id",
        parameters: &[],
        return_type: "text",
        documentation: "*Core*\n\nCheck-in identifier of the SQLite source.",
    },
    FunctionSignature {
        name: "sqlite_version",
        parameters: &[],
        return_type: "text",
        documentation: "*Core*\n\nVersion string of the SQLite library.",
    },
    FunctionSignature {
        name: "sqrt",
        parameters: &["X"],
        return_type: "real",
        documentation: "*Math*\n\nSquare root of X.",
    },
    FunctionSignature {
        name: "strftime",
        parameters: &["format", "time-value", "modifier", "..."],
        return_type: "text",
        documentation: "*Date and Time*\n\nDate formatted according to the strftime() format string.",
    },
    FunctionSignature {
        name: "string_agg",
        parameters: &["X", "Y"],
        return_type: "text",
        documentation: "*Aggregate*\n\nAll non-NULL X concatenated with separator Y (alias of group_concat).",
    },
    FunctionSignature {
        name: "substr",
        parameters: &["X", "Y"],
        return_type: "text",
        documentation: "*Core*\n\nSubstring of X starting at the Y-th character to the end.",
    },
    FunctionSignature {
        name: "substr",
        parameters: &["X", "Y", "Z"],
        return_type: "text",
        documentation: "*Core*\n\nSubstring of X that is Z characters long starting at the Y-th character.",
    },
    FunctionSignature {
        name: "substring",
        parameters: &["X", "Y"],
        return_type: "text",
        documentation: "*Core*\n\nAlias of substr().",
    },
    FunctionSignature {
        name: "substring",
        parameters: &["X", "Y", "Z"],
        return_type: "text",
        documentation: "*Core*\n\nAlias of substr().",
    },
    FunctionSignature {
        name: "subtype",
        parameters: &["X"],
        return_type: "integer",
        documentation: "*Extension*\n\nSubtype of the value X (JSON uses subtype 74).",
    },
    FunctionSignature {
        name: "sum",
        parameters: &["X"],
        return_type: "",
        documentation: "*Aggregate*\n\nSum of all non-NULL X; NULL when there are none.",
    },
    FunctionSignature {
        name: "tan",
        parameters: &["X"],
        return_type: "real",
        documentation: "*Math*\n\nTangent of X (radians).",
    },
    FunctionSignature {
        name: "tanh",
        parameters: &["X"],
        return_type: "real",
        documentation: "*Math*\n\nHyperbolic tangent of X.",
    },
    FunctionSignature {
        name: "time",
        parameters: &["time-value", "modifier", "..."],
        return_type: "text",
        documentation: "*Date and Time*\n\nTime as HH:MM:SS.",
    },
    FunctionSignature {
        name: "timediff",
        parameters: &["time-value", "time-value"],
        return_type: "text",
        documentation: "*Date and Time*\n\nDifference between two times as +YYYY-MM-DD HH:MM:SS.SSS.",
    },
    FunctionSignature {
        name: "total",
        parameters: &["X"],
        return_type: "real",
        documentation: "*Aggregate*\n\nSum of all non-NULL X as a floating point value; 0.0 when there are none.",
    },
    FunctionSignature {
        name: "total_changes",
        parameters: &[],
        return_type: "integer",
        documentation: "*Core*\n\nNumber of rows modified by all INSERT, UPDATE and DELETE statements since the connection opened.",
    },
    FunctionSignature {
        name: "trim",
        parameters: &["X"],
        return_type: "text",
        documentation: "*Core*\n\nX with leading and trailing spaces removed.",
    },
    FunctionSignature {
        name: "trim",
        parameters: &["X", "Y"],
        return_type: "text",
        documentation: "*Core*\n\nX with leading and trailing characters in Y removed.",
    },
    FunctionSignature {
        name: "trunc",
        parameters: &["X"],
        return_type: "integer",
        documentation: "*Math*\n\nX truncated towards zero.",
    },
    FunctionSignature {
        name: "typeof",
        parameters: &["X"],
        return_type: "text",
        documentation: "*Core*\n\nDatatype of X: null, integer, real, text or blob.",
    },
    FunctionSignature {
        name: "unhex",
        parameters: &["X"],
        return_type: "blob",
        documentation: "*Core*\n\nBLOB decoded from the hexadecimal string X.",
    },
    FunctionSignature {
        name: "unhex",
        parameters: &["X", "Y"],
        return_type: "blob",
        documentation: "*Core*\n\nBLOB decoded from X, ignoring the characters in Y.",
    },
    FunctionSignature {
        name: "unicode",
        parameters: &["X"],
        return_type: "integer",
        documentation: "*Core*\n\nUnicode code point of the first character of X.",
    },
    FunctionSignature {
        name: "unixepoch",
        parameters: &["time-value", "modifier", "..."],
        return_type: "integer",
        documentation: "*Date and Time*\n\nSeconds since 1970-01-01 00:00:00 UTC.",
    },
    FunctionSignature {
        name: "unlikely",
        parameters: &["X"],
        return_type: "",
        documentation: "*Core*\n\nReturns X; hints the planner that X is usually false.",
    },
    FunctionSignature {
        name: "upper",
        parameters: &["X"],
        return_type: "text",
        documentation: "*Core*\n\nX with ASCII characters converted to upper case.",
    },
    FunctionSignature {
        name: "zeroblob",
        parameters: &["N"],
        return_type: "blob",
        documentation: "*Core*\n\nBLOB consisting of N bytes of 0x00.",
    },
];
